apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-env
  namespace: berk
  labels:
    dgpays: learning
spec:
  replicas: 1
  selector:
    matchLabels:
      dgpays: learning
  template:
    metadata:
      labels:
        dgpays: learning
    spec:
      containers:
      - name: secret-env
        image: harbor.dgpays.local/docker.io/library/nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        envFrom:
        - secretRef:
            name: from-yaml
        volumeMounts: 
          - name: secret-file
            mountPath: /tmp/berk
            readOnly: true
      volumes:
        - name: secret-file
          secret:
            secretName: my-secret